


- name: docker login 
  docker_login: 
    username: "{{ docker_user }}"
    password: "{{ docker_pass }}"
    email: docker@docker.io

- name: docker image pull 
  docker_image: 
    name: "{{ image_name  }}"
    tag: "{{image_tag}}"
